# Site settings
title: Welcome!
email: ziyan.xzy@alibaba-inc.com
description: "This is a beta version of my blog, I'll consummate it as soon as I can."
baseurl: ""
url: "http://xuziyan001.github.io"
weibo_username: 葡萄小芄吇_333
github_username:  xuziyan001

# Build settings
highlighter: pygments
#auto: true
markdown: redcarpet
permalink: pretty

